name: 'Automated Flysystem Maintenance'
description: 'Automated maintenance tasks for Flysystem (monorepo and sub-splits)'
author: 'Frank de Jonge'
branding:
  icon: shield
  color: gray-dark
inputs:
  message:
    description: 'Comment to post under invalid PRs'
    required: true
  target_branch_match:
    description: 'Regex pattern to match which branches to target'
    required: false
    default: '.*'
  access-token:
    description: 'Access-token for the repository. Can be supplied using `{{ secrets.GH_PAT }}`.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
