name: 'Automated Flysystem Maintenance'
description: 'Automated maintenance tasks for Flysystem (monorepo and sub-splits)'
author: 'Frank de Jonge'
inputs:
  access-token:
    description: 'Access-token for the repository. Can be supplied using `{{ secrets.GH_PAT }}`.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
